export enum COMMANDS
{
    ADD="--add",
    CREATE="--create",
    CREATE_MIT_IGNORE="-ig",
    DELETE="--delete",
    DELETE_DONE="-d",
    DONE="--done",
    HELP_LONG="--help",
    HELP_SHORT="-h",
    HIDE="--hide",
    IGNORE="--ignore",
    NOT_IGNORE="-n",
    RESET_LONG="--reset",
    RESET_SHORT="-r",
    SHOW="--show",
    SHOW_ONLY_DONE="-d",
    SHOW_HIDDEN="-hidden",
}
